### ISSUE TITLE
Which file has the main decision making process?

### ISSUE THREAD

**Issue by alexanderkoumis** [h-e-n-r-y/binance-marketmaker#3]
Sorry, I know this is a bit lazy, I have crawled through the source and haven't found the "meat" yet. How do you decide if it is better to cancel your orders rather than leave them open? Where are you calculating spreads and taking into account fees? Thanks!

**Comment by h-e-n-r-y** [comment]
Hi, 

the meat is in TraderImpl.proposeTradingAction(). It is very simple. It does not cancel orders, but only makes new orders or waits for execution (or manual cancel). If a Task is active, then a new order is created after execution.

Henry

**Comment by anhtuantt** [comment]
Hello,
Thank you for your code contribution, I just deployed and tried your project and got the error at hiting button "Trade", Could you help me do a quick fix.

Thanks a lot,
Tuan Nguyen.

Internal Server Error
com.fasterxml.jackson.databind.exc.InvalidFormatException: Can not deserialize value of type com.binance.api.client.domain.general.RateLimitType from String "REQUEST_WEIGHT": value not one of declared Enum instance names: [REQUESTS, ORDERS] at [Source: okhttp3.ResponseBody$BomAwareReader@1aeb72ab; line: 1, column: 77] (through reference chain: com.binance.api.client.domain.general.ExchangeInfo["rateLimits"]->java.util.ArrayList[0]->com.binance.api.client.domain.general.RateLimit["rateLimitType"])
