### ISSUE TITLE
Unable to create a trade

### ISSUE THREAD

**Issue by anhtuantt** [h-e-n-r-y/binance-marketmaker#5]
Hello,
Thank you for your code contribution, I just deployed and tried your project and got the error at hiting button "Trade", Could you help me do a quick fix.

Thanks a lot,
Tuan Nguyen.

Internal Server Error
com.fasterxml.jackson.databind.exc.InvalidFormatException: Can not deserialize value of type com.binance.api.client.domain.general.RateLimitType from String "REQUEST_WEIGHT": value not one of declared Enum instance names: [REQUESTS, ORDERS] at [Source: okhttp3.ResponseBody$BomAwareReader@1aeb72ab; line: 1, column: 77] (through reference chain: com.binance.api.client.domain.general.ExchangeInfo["rateLimits"]->java.util.ArrayList[0]->com.binance.api.client.domain.general.RateLimit["rateLimitType"])

**Comment by h-e-n-r-y** [comment]
Hi,

sorry for this. I noticed this error on my own server. I guess there was a change on the official API that I have to integrate. I will do that soon and will notify you than. Thanks for your patience!

Henry

**Comment by h-e-n-r-y** [comment]
Hello,

please pull and rebuild the binance-java-api library by issuing following commands:

`cd ~/git`
`cd binance-java-api`
`git pull`
`mvn install`

After that the market-maker can be pulled and restarted and the errors should be gone.

Please let me know if it works...

Henry

**Comment by anhtuantt** [comment]
Thank you for you quick fix. Just do a quick test on my local machine and got the error "Timestamp for this request was 1000ms ahead of the server's time.", it's very common issue of Binance, so I will retest the latest code later.

**Comment by anhtuantt** [comment]
It worked well.
